require("configs.keymaps")
require("configs.options")
require("configs.plugins")
require("configs.autocommand")
require("configs.colorscheme")
require("configs.whichkey")
require("configs.treesitter")
require("configs.telescope")
require("configs.cmp")
require("configs.toggleterm")
require("configs.colorizer")
require("configs.formatter")
require("configs.comment")
require("configs.indentlines")
require("configs.chatbot")
require("configs.tabby")
require("configs.lsp")
-- require("configs.statusline")
require("leap").add_default_mappings()
vim.keymap.set({ "n", "x", "o" }, "f", "<Plug>(leap-forward-to)")
